/*
 * @Author: Ender-Wiggin
 * @Date: 2025-02-01 11:39:06
 * @LastEditors: Ender-Wiggin
 * @LastEditTime: 2025-02-02 21:56:49
 * @Description:
 */
import { NextIntlClientProvider } from "next-intl";
import Image from "next/image";
import { getMessages } from "next-intl/server";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Link, routing } from "@/i18n/routing";
import { Bangers, ZCOOL_KuaiLe } from "next/font/google";
import {setRequestLocale} from 'next-intl/server';

import "./globals.css";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

const bangers = Bangers({
	weight: "400",
	subsets: ["latin"],
});

const zcool = ZCOOL_KuaiLe({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
	// Ensure that the incoming `locale` is valid
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	if (!routing.locales.includes(locale as any)) {
		notFound();
	}

	const messages = await getMessages();
	return (
		<html lang="en">
			<body
				className={`${
					locale === "en" ? bangers.className : zcool.className
				} antialiased bg-bg min-h-screen flex flex-col py-1`}
			>
				<div className="flex justify-center items-center from-current to-transparent">
					<Image src="/assets/logo.png" width={100} height={100} alt="logo" />
				</div>
				<main className="flex-1 px-2">
					<NextIntlClientProvider messages={messages}>
						{children}
					</NextIntlClientProvider>
				</main>
				<footer className="w-full py-4">
					<div className="container mx-auto px-2 flex justify-between gap-4">
          <Link href={"/generator"} className="text-white underline hover:underline">
							Generator
						</Link>
						<Link href={"/card-list"} className="text-white underline hover:underline">
							Card List
						</Link>
            <Link href={"https://docs.google.com/spreadsheets/d/1VxIXf5RiGQGDnk4eoLz4tDqIaKmzvNnropPOSWjrh2w/edit?usp=sharing"} className="text-white underline hover:underline">
							Add More Cards
						</Link>
            <Link href={"/card-list"} className="text-white underline hover:underline">
							Help Translate
						</Link>
					</div>
				</footer>
			</body>
		</html>
	);
}
